### ISSUE TITLE
Check with CDS why GetStar fails on some targets

### ISSUE THREAD

**Issue by gmella** [JMMC-OpenDev/sclgui#1]
Vizier queries fail when no rows returned: bad encoding of xml document!

See 
http://vizier.u-strasbg.fr/viz-bin/asu-xml?-source=I/280&-out.meta=hudU1&-oc.form=sexa&-c.eq=J2000&-out.add=_RAJ2000&-out.add=_DEJ2000&-oc=hms&-out.max=1000&-sort=_r&-c.rs=4.5&-out.add=_1&-file=-c&-out=e_RAJ2000&-out=e_DEJ2000&-out=HIP&-out=HD&-out=DM&-out=TYC1&-out=TYC2&-out=TYC3&-out=pmRA&-out=e_pmRA&-out=pmDE&-out=e_pmDE&-out=Bmag&-out=e_Bmag&-out=Vmag&-out=e_Vmag&-out=v1&-out=v2&-out=v3&-out=d5&-out.form=List&-c=%3C%3C%3D%3D%3D%3DLIST&242.880638-18.640479&%3D%3D%3D%3DLIST

[vizier_votable.zip](https://github.com/JMMC-OpenDev/sclgui/files/9599118/vizier_votable.zip)

**Comment by gilleslandais** [comment]
I confirm - 
It needs a VizieR patch to fix it - 

This issue concerns list of position when the option -out.add=_1 is used.
In the last version  the behavior changed when nothing is found for a position in the list, now an empty record is displayed (except _1 column containing the position).
There is indeed an error with astrores output. I will fix it !

**Comment by gilleslandais** [comment]
new beta version  is available @ http://viz-beta.u-strasbg.fr/viz-bin/VizieR
The version should fix your issue:  can you check ?

**Comment by gilleslandais** [comment]
(sorry for this update) 
I would be very happy if you can update your c-code  :-)

**Comment by bourgesl** [comment]
Merci Gilles pour les corrections sur Vizier,
Super efficace,
Laurent
